/* ------------------------------------------ DROP DE PROCEDURES ------------------------------------------ */


--- ACA LA DE CARACTERISTICA - esta hecho pero lo hizo andy
--- ACA LA DE AMBIENTE
--- ACA ANUNCIO
--- ACA ALQUILER
--- ACA VENTA
--- ACA INMUEBLE


IF OBJECT_ID('LOS_GDDS.MIGRAR_Inmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Inmueble
GO



IF OBJECT_ID('LOS_GDDS.MIGRAR_Provincia') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Provincia
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Localidad') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Localidad
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Barrio') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Barrio
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Sucursal') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Sucursal
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Agente') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Agente
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Disposicion') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Disposicion
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_EstadoInmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_EstadoInmueble
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_TipoInmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_TipoInmueble
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Orientacion') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Orientacion
GO


IF OBJECT_ID('LOS_GDDS.MIGRAR_PROPIETARIO') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_PROPIETARIO
GO


IF OBJECT_ID('LOS_GDDS.MIGRAR_EstadoAnuncio') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_EstadoAnuncio
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Operacion') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Operacion
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_TipoPeriodo') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_TipoPeriodo
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Moneda') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Moneda
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_MedioPago') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_MedioPago
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_PagoVenta') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_PagoVenta
GO

IF OBJECT_ID('LOS_GDD.MIGRAR_Comprador') IS NOT NULL
	DROP PROCEDURE LOS_GDD.MIGRAR_Comprador
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_DetalleAlquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_DetalleAlquiler
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Inquilino') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Inquilino
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_EstadoAlquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_EstadoAlquiler
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_DetalleAlquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_DetalleAlquiler
GO
