/* ------------- EJECUCION DE PROCEDURES ---------------- */

EXEC LOS_GDDS.MIGRAR_BI_Provincia ---OK
EXEC LOS_GDDS.MIGRAR_BI_Localidad--OK
EXEC LOS_GDDS.MIGRAR_BI_Barrio--CHEQUEAR

EXEC LOS_GDDS.MIGRAR_BI_PROPIETARIO ---OK

EXEC LOS_GDDS.MIGRAR_BI_Sucursal---OK

EXEC LOS_GDDS.MIGRAR_BI_Agente---OK

EXEC LOS_GDDS.MIGRAR_BI_Disposicion ---OK
EXEC LOS_GDDS.MIGRAR_BI_EstadoInmueble---OK
EXEC LOS_GDDS.MIGRAR_BI_TipoInmueble --OK
EXEC LOS_GDDS.MIGRAR_BI_Orientacion --OK


EXEC LOS_GDDS.MIGRAR_BI_Ambiente-- OK
EXEC LOS_GDDS.MIGRAR_BI_Inmueble -- OK
EXEC LOS_GDDS.MIGRAR_BI_Caracteristica-- OK
EXEC LOS_GDDS.MIGRAR_BI_AmbienteInmueble --OK 
EXEC LOS_GDDS.MIGRAR_BI_CaracteristicaInmueble --OK



EXEC LOS_GDDS.MIGRAR_BI_EstadoAnuncio---OK


EXEC LOS_GDDS.MIGRAR_BI_Operacion---OK
EXEC LOS_GDDS.MIGRAR_BI_TipoPeriodo---OK
EXEC LOS_GDDS.MIGRAR_BI_Moneda---OK
EXEC LOS_GDDS.MIGRAR_BI_MedioPago---OK

EXEC LOS_GDDS.MIGRAR_BI_Inquilino---OK
EXEC LOS_GDDS.MIGRAR_BI_EstadoAlquiler---OK

EXEC LOS_GDDS.MIGRAR_BI_Anuncio --OK
EXEC LOS_GDDS.MIGRAR_BI_Alquiler --OK

EXEC LOS_GDDS.MIGRAR_BI_DetalleAlquiler -- OK
EXEC LOS_GDDS.MIGRAR_BI_PagoAlquiler --OK

EXEC LOS_GDDS.MIGRAR_BI_Comprador  
EXEC LOS_GDDS.MIGRAR_BI_Venta --OK
EXEC LOS_GDDS.MIGRAR_BI_PagoVenta


EXEC LOS_GDDS.MIGRAR_BIRANGO_ETARIO

EXEC LOS_GDDS.MIGRAR_BI_Ubicacion

EXEC LOS_GDDS.MIGRAR_BI_Tiempo
