/* ------------------------------------------ DROP DE PROCEDURES ------------------------------------------ */

IF OBJECT_ID('LOS_GDDS.MIGRAR_Ambiente') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Ambiente
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Alquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Alquiler
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_PagoAlquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_PagoAlquiler
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Venta') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Venta
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Anuncio') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Anuncio
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Caracteristica') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Caracteristica
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_CaracteristicaInmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_CaracteristicaInmueble
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Ambiente') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Ambiente
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_AmbienteInmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_AmbienteInmueble
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Inmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Inmueble
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Provincia') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Provincia
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Localidad') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Localidad
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Barrio') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Barrio
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Sucursal') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Sucursal
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Agente') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Agente
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Disposicion') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Disposicion
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_EstadoInmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_EstadoInmueble
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_TipoInmueble') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_TipoInmueble
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Orientacion') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Orientacion
GO


IF OBJECT_ID('LOS_GDDS.MIGRAR_PROPIETARIO') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_PROPIETARIO
GO


IF OBJECT_ID('LOS_GDDS.MIGRAR_EstadoAnuncio') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_EstadoAnuncio
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Operacion') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Operacion
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_TipoPeriodo') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_TipoPeriodo
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Moneda') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Moneda
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_MedioPago') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_MedioPago
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_PagoVenta') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_PagoVenta
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Comprador') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Comprador
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_DetalleAlquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_DetalleAlquiler
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_Inquilino') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_Inquilino
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_EstadoAlquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_EstadoAlquiler
GO

IF OBJECT_ID('LOS_GDDS.MIGRAR_DetalleAlquiler') IS NOT NULL
	DROP PROCEDURE LOS_GDDS.MIGRAR_DetalleAlquiler
GO
