/* ------------- EJECUCION DE PROCEDURES ---------------- */

EXEC LOS_GDDS.MIGRAR_Provincia ---OK
EXEC LOS_GDDS.MIGRAR_Localidad--OK
EXEC LOS_GDDS.MIGRAR_Barrio--CHEQUEAR

EXEC LOS_GDDS.MIGRAR_PROPIETARIO ---OK

EXEC LOS_GDDS.MIGRAR_Sucursal---OK

EXEC LOS_GDDS.MIGRAR_Agente---OK

EXEC LOS_GDDS.MIGRAR_Disposicion ---OK
EXEC LOS_GDDS.MIGRAR_EstadoInmueble---OK
EXEC LOS_GDDS.MIGRAR_TipoInmueble --OK
EXEC LOS_GDDS.MIGRAR_Orientacion --OK


EXEC LOS_GDDS.MIGRAR_Ambiente-- OK
EXEC LOS_GDDS.MIGRAR_Inmueble -- OK
EXEC LOS_GDDS.MIGRAR_Caracteristica-- OK
EXEC LOS_GDDS.MIGRAR_AmbienteInmueble --OK 
EXEC LOS_GDDS.MIGRAR_CaracteristicaInmueble --OK



EXEC LOS_GDDS.MIGRAR_EstadoAnuncio---OK


EXEC LOS_GDDS.MIGRAR_Operacion---OK
EXEC LOS_GDDS.MIGRAR_TipoPeriodo---OK
EXEC LOS_GDDS.MIGRAR_Moneda---OK
EXEC LOS_GDDS.MIGRAR_MedioPago---OK

EXEC LOS_GDDS.MIGRAR_Inquilino---OK
EXEC LOS_GDDS.MIGRAR_EstadoAlquiler---OK

EXEC LOS_GDDS.MIGRAR_Anuncio --OK
EXEC LOS_GDDS.MIGRAR_Alquiler --OK

EXEC LOS_GDDS.MIGRAR_DetalleAlquiler -- hay filas con muchos NULLS
EXEC LOS_GDDS.MIGRAR_PagoAlquiler --OK

EXEC LOS_GDDS.MIGRAR_Comprador  
EXEC LOS_GDDS.MIGRAR_Venta --OK
EXEC LOS_GDDS.MIGRAR_PagoVenta




