
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_TipoInmueble;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Ambiente;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Tipo_Moneda;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Tipo_Operacion;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_RANGO_ETARIO;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_RANGO_M2;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Ubicacion;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Tiempo;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Sucursal;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Venta;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_Anuncio;
DROP PROCEDURE LOS_GDDS.MIGRAR_BI_PagoAlquiler;
