/* ------------- EJECUCION DE PROCEDURES ---------------- */

EXEC LOS_GDDS.MIGRAR_BI_TipoInmueble
EXEC LOS_GDDS.MIGRAR_BI_Ambiente


EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_Tipo_Moneda

EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_Tipo_Operacion

EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_RANGO_ETARIO

EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_RANGO_M2

EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_Ubicacion

EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_Tiempo

EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_Sucursal

EXEC PROCEDURE LOS_GDDS.MIGRAR_BI_Venta
