/* ------------- EJECUCION DE PROCEDURES ---------------- */

EXEC LOS_GDDS.MIGRAR_BI_TipoInmueble

EXEC LOS_GDDS.MIGRAR_BI_Ambiente

EXEC LOS_GDDS.MIGRAR_BI_Tipo_Moneda

EXEC LOS_GDDS.MIGRAR_BI_Tipo_Operacion

EXEC LOS_GDDS.MIGRAR_BI_RANGO_ETARIO

EXEC LOS_GDDS.MIGRAR_BI_RANGO_M2

EXEC LOS_GDDS.MIGRAR_BI_Ubicacion

EXEC LOS_GDDS.MIGRAR_BI_Tiempo

EXEC LOS_GDDS.MIGRAR_BI_Sucursal

EXEC LOS_GDDS.MIGRAR_BI_Anuncio

EXEC LOS_GDDS.MIGRAR_BI_Venta

EXEC LOS_GDDS.MIGRAR_BI_PagoAlquiler

EXEC LOS_GDDS.MIGRAR_BI_Alquiler