-- Tablas de Hechos
TRUNCATE TABLE LOS_GDDS.BI_Venta

TRUNCATE TABLE LOS_GDDS.BI_Alquiler

TRUNCATE TABLE LOS_GDDS.BI_Anuncio 

TRUNCATE TABLE LOS_GDDS.BI_PagoAlquiler 


-- Tablas de Dimensiones
-- TRUNCATE TABLE LOS_GDDS.BI_Tiempo

-- TRUNCATE TABLE LOS_GDDS.BI_Ubicacion

-- TRUNCATE TABLE LOS_GDDS.BI_Sucursal

-- TRUNCATE TABLE LOS_GDDS.BI_RANGO_ETARIO

-- TRUNCATE TABLE LOS_GDDS.BI_RANGO_M2

-- TRUNCATE TABLE LOS_GDDS.BI_Tipo_inmueble

-- TRUNCATE TABLE LOS_GDDS.BI_Ambiente

-- TRUNCATE TABLE LOS_GDDS.BI_Tipo_Operacion

-- TRUNCATE TABLE LOS_GDDS.BI_Tipo_Moneda